spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: guscjf0903
    password: tnthtn35
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c96ug4gikmm4.ap-northeast-2.rds.amazonaws.com:5432/allergySafeDB
    username: guscjf0903
    password: tnthtn35
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect