server:
  port: 7777

jwt:
  secret-key: "3okpDDRf6HCajVusuiLSVWaAbqHdV/V7V44LIRAZeaBtSGoSi+vDK1uewFHYSmnIs6+vzq0+3ZxV4OdztVCj+g==
"
---
spring:
  devtools:
    livereload:
      enabled: false
  jpa:
    properties:
      hibernate:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true


  profiles:
    group:
      dev:
        - db-dev
        - openinview-dev
        - openApi
        - gmail
        - redis
        - s3
      prod:
        - db-prod
        - openinview-prod
        - gmail
        - openApi
        - redis
        - s3


    include:
      - db
