spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: guscjf0903@gmail.com
    password: etib vrpc odsx hnmj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        auth-code-expiration-millis: 180000
