spring:
  config:
    activate:
      on-profile: prod

cloud:
  aws:
    s3:
      bucket: allergysafe-bucket
    stack.auto: false

    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}