server:
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    group:
      dev: profile1
      prod: profile2
---
spring:
  config:
    activate:
      on-profile: profile1

api:
  url: http://localhost:7777

ui:
  url: http://localhost:8888

---
spring:
  config:
    activate:
      on-profile: profile2
api:
  url: http://ec2-54-180-102-86.ap-northeast-2.compute.amazonaws.com:7777

ui:
  url: http://ec2-54-180-102-86.ap-northeast-2.compute.amazonaws.com:8888
